nginx:
  image: nginx:1.11.1
  ports:
    - "8888:8888"
    - "8889:8889"
  environment:
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: Admin
    ADMIN_LASTNAME: Inistrator
    ADMIN_PASSWORD: password123
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
  links:
      - "php:php"
  volumes:
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
  volumes_from:
    - php
php:
  build: images/php
  links:
    - "mysql:mysql"
  volumes:
      - ./www:/var/www/html:rw
mysql:
  image: mysql:5.7.13
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: magentostore
    MYSQL_DATABASE: magentostore
    MYSQL_USER: magentostore
    MYSQL_PASSWORD: magentostore
  volumes:
    - ./database/magento_sample_data_for_1.9.1.0.sql:/docker-entrypoint-initdb.d/schema.sql
