nginxphpfpm:
  image: nginx:1.11.1
  ports:
    - "7777:7777"
    - "8889:8889"
    - "8888:8888"

  ulimits:
      nofile:
        soft: 100000
        hard: 100000
  environment:
    ADMIN_USERNAME: admin
    ADMIN_FIRSTNAME: Admin
    ADMIN_LASTNAME: Inistrator
    ADMIN_PASSWORD: password123
    ADMIN_FRONTNAME: admin
    ADMIN_EMAIL: admin@example.com
    ENCRYPTIONKEY: 731aea833710535779fe8c7c49bc6c4d
  links:
      - "phpfpm:php"
  volumes:
    - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./config/nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
  volumes_from:
      - phpfpm
phpfpm:
  build: images/php
  links:
    - "mysqlphpfpm:mysql"
  ulimits:
      nofile:
        soft: 100000
        hard: 100000
  volumes:
      - ./www:/var/www/html:rw
      - ./tmp:/tmp:rw
mysqlphpfpm:
  image: mysql:5.7.13
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: magentostore
    MYSQL_DATABASE: magentostore
    MYSQL_USER: magentostore
    MYSQL_PASSWORD: magentostore
  volumes:
    - ./database/magento_sample_data_for_1.9.1.0.sql:/docker-entrypoint-initdb.d/schema.sql
